### ISSUE TITLE
Examples need updating

### ISSUE THREAD

**Issue by johnareid54** [Ethiel97/nice_intro#1]
I have just tried to load the example version and had the following problem:

- The parameter 'onSkip' is required. .
- The parameter 'onDone' is required. .

I think this is because you have not updated the example code.

Also if I put in the device into landscape mode the layout is distorted. Do you have any plans to improve the landscape layout?

**Comment by Ethiel97** [comment]
Hello buddy,

Thanks for the feedback. I'll update the example file and handle the
landscape mode.

Did you read the doc of the package?

Cheers,
Ethiel ADIASSA.

Consultant Développeur informatique (Fullstack Web et Mobile)

**Comment by johnareid54** [comment]
**Did you read the doc of the package?**

Like most computer guys I quickly glanced at the docs, I just wanted to paste in your example and see what it looked like on a device. I first tried the example in pub.dev but the two imports were not found:
import 'package:intro_screen/intro_screens.dart';
import 'package:intro_screen/page_view_model.dart';

Thanks for looking into the landscape issue, I always regard the end-users as being totally stupid and doing things you least expect.

**Comment by Ethiel97** [comment]
Yes you are right. Let me update the doc.

Consultant Développeur informatique (Fullstack Web et Mobile)

**Comment by Ethiel97** [comment]
The package is updated. You can check again.
Thanks for your useful feedback.

Cheers,
Ethiel.

Consultant Développeur informatique (Fullstack Web et Mobile)

**Comment by johnareid54** [comment]
Thanks a lot better, but the landscape needs more design..

![image](https://user-images.githubusercontent.com/53974881/80381936-92a6cc00-8899-11ea-9547-c87a1fdd2777.png)
